      const PRODUCTS = [
        {
          id: 1,
          category: "Motors",
          verified: true,
          msme: true,
          name: "BM-5010 Brushless Motor",
          desc: "High-torque outrunner motor for multirotor UAV platforms. Precision balanced rotors, corrosion-resistant casing.",
          sku: "BM-MTR-5010-KV360",
          specs: [
            ["Motor Type", "Brushless Outrunner"],
            ["KV Rating", "360 KV"],
            ["Shaft Diameter", "6 mm"],
            ["Stator Size", "50×10 mm"],
            ["Weight", "175 g"],
            ["Max Thrust", "2800 g"],
            ["Compatibility", "6S LiPo"],
          ],
          elec: [
            ["Operating Voltage", "22.2 V (6S)"],
            ["Max Current", "42 A"],
            ["Internal Resistance", "38 mΩ"],
            ["Power Rating", "930 W"],
            ["Efficiency", "> 85%"],
            ["No-load Current", "0.8 A"],
          ],
          certs: [
            "Bharat Verified OEM Certification",
            "MSME Registration No. IND-MH-2021-009",
            "Factory Licence No. FL/MH/2020/14482",
            "CoC – Grade 7075 Aluminium Bell",
          ],
          compliance: [
            ["Standard", "IS/IEC 60034-1"],
            ["RoHS", "Compliant"],
            ["Proof of Origin", "Maharashtra, India"],
            ["Audit Ready", "Yes – full traceability"],
          ],
        },
        {
          id: 2,
          category: "ESC",
          verified: true,
          msme: false,
          name: "BM-45A 4-in-1 ESC",
          desc: "Compact 4-in-1 electronic speed controller for racing and industrial quads. BLHeli_32 firmware compatible.",
          sku: "BM-ESC-45A-4IN1",
          specs: [
            ["Type", "4-in-1 ESC"],
            ["Continuous Current", "45A per channel"],
            ["Burst Current", "55A (10 sec)"],
            ["BEC Output", "5V / 2A"],
            ["Size", "38×38 mm"],
            ["Weight", "14.5 g"],
            ["Firmware", "BLHeli_32"],
          ],
          elec: [
            ["Input Voltage", "3–6S LiPo"],
            ["PWM Frequency", "8–48 kHz"],
            ["Telemetry", "UART / Dshot"],
            ["Motor Support", "2–8 poles"],
            ["Idle Rate", "3.5%"],
            ["Braking", "Active / Passive"],
          ],
          certs: [
            "Bharat Verified OEM Certification",
            "Factory Licence No. FL/KA/2022/08811",
            "CoC – PCB Grade FR4 TG180",
          ],
          compliance: [
            ["Standard", "IPC-6012 Class 3"],
            ["RoHS", "Compliant"],
            ["Proof of Origin", "Karnataka, India"],
            ["Audit Ready", "Yes"],
          ],
        },
        {
          id: 3,
          category: "Flight Controllers",
          verified: true,
          msme: true,
          name: "BM-FC7 Flight Controller",
          desc: "STM32F7-based flight controller with dual IMU redundancy. Designed for defence-grade UAV reliability.",
          sku: "BM-FC7-H743",
          specs: [
            ["MCU", "STM32H743 480 MHz"],
            ["IMU", "Dual ICM-42688-P"],
            ["Barometer", "BMP388"],
            ["Connectors", "6× UARTs, 13× PWM"],
            ["Dimensions", "40×40 mm"],
            ["Weight", "9 g"],
            ["Stack Mount", "M3 30.5×30.5 mm"],
          ],
          elec: [
            ["Input Voltage", "5V (regulated)"],
            ["Current Draw", "250 mA typical"],
            ["Flash", "2 MB"],
            ["RAM", "1 MB"],
            ["USB", "Micro-USB / USB-C"],
            ["Logging", "MicroSD blackbox"],
          ],
          certs: [
            "Bharat Verified OEM Certification",
            "MSME Registration No. IND-TN-2022-0341",
            "Factory Licence No. FL/TN/2021/33201",
            "CoC – Military-Grade PCB Substrate",
          ],
          compliance: [
            ["Standard", "IPC-6012 Class 3"],
            ["RoHS", "Compliant"],
            ["EMC", "MIL-STD-461F"],
            ["Proof of Origin", "Tamil Nadu, India"],
            ["Audit Ready", "Yes – full traceability"],
          ],
        },
        {
          id: 4,
          category: "Battery",
          verified: true,
          msme: true,
          name: "BM-6S 22000mAh LiPo",
          desc: "High-density 6S LiPo battery pack for heavy-lift UAV operations. BMS-protected with cycle-life monitoring.",
          sku: "BM-BAT-6S-22AH-15C",
          specs: [
            ["Cell Configuration", "6S1P (22.2 V nominal)"],
            ["Capacity", "22,000 mAh"],
            ["Discharge Rate", "15C continuous"],
            ["Peak Discharge", "30C (10 sec)"],
            ["Dimensions", "192×80×60 mm"],
            ["Weight", "2.35 kg"],
            ["Connector", "AS150 / XT150"],
          ],
          elec: [
            ["Nominal Voltage", "22.2 V"],
            ["Full Charge Voltage", "25.2 V"],
            ["Cutoff Voltage", "18.0 V"],
            ["Max Charge Rate", "1C (22 A)"],
            ["Internal Resistance", "< 8 mΩ/cell"],
            ["Cycle Life", "> 300 cycles"],
          ],
          certs: [
            "Bharat Verified OEM Certification",
            "MSME Registration No. IND-GJ-2021-4782",
            "Factory Licence No. FL/GJ/2020/29201",
            "UN38.3 Transport Test Certificate",
          ],
          compliance: [
            ["Standard", "IEC 62133-2"],
            ["UN38.3", "Pass"],
            ["Proof of Origin", "Gujarat, India"],
            ["Audit Ready", "Yes"],
          ],
        },
        {
          id: 5,
          category: "Motors",
          verified: false,
          msme: true,
          name: "BM-2306 Racing Motor",
          desc: "Ultra-lightweight 2306 stator motor for 5-inch FPV racing. Hard-anodised aluminium construction.",
          sku: "BM-MTR-2306-KV2450",
          specs: [
            ["Motor Type", "Brushless Outrunner"],
            ["KV Rating", "2450 KV"],
            ["Shaft Diameter", "3 mm"],
            ["Stator Size", "23×06 mm"],
            ["Weight", "29 g"],
            ["Max Thrust", "920 g"],
            ["Compatibility", "4S LiPo"],
          ],
          elec: [
            ["Operating Voltage", "14.8 V (4S)"],
            ["Max Current", "32 A"],
            ["Internal Resistance", "60 mΩ"],
            ["Power Rating", "475 W"],
            ["Efficiency", "> 82%"],
            ["No-load Current", "0.6 A"],
          ],
          certs: [
            "MSME Registration No. IND-MH-2020-1122",
            "CoC – 7075-T6 Aluminium Bell",
          ],
          compliance: [
            ["Standard", "IS/IEC 60034-1"],
            ["RoHS", "Compliant"],
            ["Proof of Origin", "Maharashtra, India"],
            ["Audit Ready", "Partial"],
          ],
        },
        {
          id: 6,
          category: "3D Printing",
          verified: true,
          msme: false,
          name: "BM-CF-PETG Filament",
          desc: "Carbon-fibre reinforced PETG filament for structural UAV frame printing. Aerospace-grade dimensional accuracy.",
          sku: "BM-3DP-CFPETG-1KG",
          specs: [
            ["Material", "CF-PETG (15% CF)"],
            ["Diameter", "1.75 mm ± 0.02 mm"],
            ["Spool Weight", "1 kg"],
            ["Print Temp", "240–260 °C"],
            ["Bed Temp", "70–80 °C"],
            ["Layer Adhesion", "Excellent"],
            ["Colour", "Matte Black"],
          ],
          elec: [
            ["Tensile Strength", "68 MPa"],
            ["Flexural Modulus", "4.2 GPa"],
            ["Impact Resistance", "High"],
            ["Moisture Absorption", "< 0.1%"],
            ["Heat Deflection", "82 °C"],
            ["Density", "1.34 g/cm³"],
          ],
          certs: [
            "Bharat Verified OEM Certification",
            "CoC – CF Reinforcement Ratio",
            "Material Safety Data Sheet (MSDS)",
          ],
          compliance: [
            ["Standard", "ISO 527-2"],
            ["RoHS", "Compliant"],
            ["Proof of Origin", "Rajasthan, India"],
            ["Audit Ready", "Yes"],
          ],
        },
        {
          id: 7,
          category: "Battery",
          verified: true,
          msme: true,
          name: "BM-4S 10000mAh Smart Pack",
          desc: "Intelligent 4S LiPo with integrated fuel gauge and temperature telemetry. Ideal for autonomous platforms.",
          sku: "BM-BAT-4S-10AH-20C",
          specs: [
            ["Cell Configuration", "4S1P (14.8 V nominal)"],
            ["Capacity", "10,000 mAh"],
            ["Discharge Rate", "20C continuous"],
            ["Peak Discharge", "40C (5 sec)"],
            ["Dimensions", "145×52×44 mm"],
            ["Weight", "0.89 kg"],
            ["Connector", "XT60 / XT90"],
          ],
          elec: [
            ["Nominal Voltage", "14.8 V"],
            ["Full Charge Voltage", "16.8 V"],
            ["Cutoff Voltage", "12.0 V"],
            ["Max Charge Rate", "2C (20 A)"],
            ["Internal Resistance", "< 6 mΩ/cell"],
            ["Cycle Life", "> 500 cycles"],
          ],
          certs: [
            "Bharat Verified OEM Certification",
            "MSME Registration No. IND-RJ-2022-0087",
            "UN38.3 Transport Test Certificate",
            "CoC – Grade A Lithium Cells",
          ],
          compliance: [
            ["Standard", "IEC 62133-2"],
            ["UN38.3", "Pass"],
            ["Proof of Origin", "Rajasthan, India"],
            ["Audit Ready", "Yes"],
          ],
        },
        {
          id: 8,
          category: "ESC",
          verified: true,
          msme: true,
          name: "BM-80A Single ESC",
          desc: "High-power single ESC for industrial motors and heavy-lift platforms. IP54-rated sealed casing.",
          sku: "BM-ESC-80A-SINGLE",
          specs: [
            ["Type", "Single ESC"],
            ["Continuous Current", "80A"],
            ["Burst Current", "100A (10 sec)"],
            ["BEC Output", "5.3V / 5A"],
            ["Size", "53×30×14 mm"],
            ["Weight", "58 g"],
            ["Firmware", "Custom BM-Ctrl v2"],
          ],
          elec: [
            ["Input Voltage", "4–12S LiPo"],
            ["PWM Frequency", "16–48 kHz"],
            ["Telemetry", "CAN bus / UART"],
            ["Motor Support", "2–24 poles"],
            ["Idle Rate", "4%"],
            ["Protection", "Over-temp / Over-current"],
          ],
          certs: [
            "Bharat Verified OEM Certification",
            "MSME Registration No. IND-MH-2022-5501",
            "Factory Licence No. FL/MH/2021/77123",
            "IP54 Ingress Protection Certificate",
          ],
          compliance: [
            ["Standard", "IPC-6012 Class 3"],
            ["IP Rating", "IP54"],
            ["Proof of Origin", "Maharashtra, India"],
            ["Audit Ready", "Yes"],
          ],
        },
        {
          id: 9,
          category: "3D Printing",
          verified: false,
          msme: true,
          name: "BM-ASA UV-Stable Filament",
          desc: "ASA filament for outdoor UAV components. Exceptional UV and weathering resistance for long-term deployments.",
          sku: "BM-3DP-ASA-1KG-GRY",
          specs: [
            ["Material", "ASA (Acrylonitrile Styrene Acrylate)"],
            ["Diameter", "1.75 mm ± 0.03 mm"],
            ["Spool Weight", "1 kg"],
            ["Print Temp", "230–250 °C"],
            ["Bed Temp", "90–100 °C"],
            ["Layer Adhesion", "Good"],
            ["Colour", "Grey"],
          ],
          elec: [
            ["Tensile Strength", "48 MPa"],
            ["Flexural Modulus", "2.1 GPa"],
            ["UV Resistance", "Excellent"],
            ["Moisture Absorption", "< 0.2%"],
            ["Heat Deflection", "95 °C"],
            ["Density", "1.07 g/cm³"],
          ],
          certs: [
            "MSME Registration No. IND-AP-2021-3301",
            "Material Safety Data Sheet (MSDS)",
            "CoC – ASA Resin Grade",
          ],
          compliance: [
            ["Standard", "ISO 527-2"],
            ["UV Stability", "Weatherometer 2000h pass"],
            ["Proof of Origin", "Andhra Pradesh, India"],
            ["Audit Ready", "Partial"],
          ],
        },
      ];
